<?php
  include_once("$KLASSEN/konstanten.php");
	include_once("$KLASSEN/elemente/aktionen.php");
	include_once("$KLASSEN/elemente/element.php");
	include_once("$KLASSEN/elemente/eingabe.php");
  include_once("$KLASSEN/icon.php");
  include_once("$KLASSEN/hinweis.php");
  include_once("$KLASSEN/elemente/knopf.php");
	include_once("$KLASSEN/struktur/seitenstruktur.php");
  include_once("$KLASSEN/laden.php");
	include_once("$KLASSEN/elemente/meldung.php");
?>